--------------------------------------------------------
--  DDL for Table APUESTAS
--------------------------------------------------------

  CREATE TABLE "SEBAS_CASINO"."APUESTAS" 
   (	"ID_APUESTA" NUMBER, 
	"ID_PARTIDA" NUMBER, 
	"TIPO_APUESTA" VARCHAR2(50 BYTE), 
	"NUMERO_APUESTA" NUMBER, 
	"MONTO" NUMBER(12,2), 
	"MULTIPLICADOR" NUMBER(12,2) DEFAULT 1, 
	"GANANCIA" NUMBER(12,2) DEFAULT 0, 
	"RESULTADO" VARCHAR2(20 BYTE) DEFAULT 'perdida'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CASINO_VIRTUAL" ;
