--------------------------------------------------------
--  Constraints for Table APUESTAS
--------------------------------------------------------

  ALTER TABLE "SEBAS_CASINO"."APUESTAS" MODIFY ("ID_PARTIDA" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."APUESTAS" MODIFY ("TIPO_APUESTA" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."APUESTAS" MODIFY ("MONTO" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."APUESTAS" ADD PRIMARY KEY ("ID_APUESTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CASINO_VIRTUAL"  ENABLE;
