--------------------------------------------------------
--  DDL for Table AUDITORIA
--------------------------------------------------------

  CREATE TABLE "SEBAS_CASINO"."AUDITORIA" 
   (	"ID_AUDITORIA" NUMBER, 
	"TABLA_AFECTADA" VARCHAR2(50 BYTE), 
	"ID_REGISTRO" NUMBER, 
	"OPERACION" VARCHAR2(10 BYTE), 
	"CAMPO" VARCHAR2(50 BYTE), 
	"VALOR_ANTERIOR" VARCHAR2(300 BYTE), 
	"VALOR_NUEVO" VARCHAR2(300 BYTE), 
	"FECHA" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"USUARIO_ORACLE" VARCHAR2(50 BYTE) DEFAULT USER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CASINO_VIRTUAL" ;
