--------------------------------------------------------
--  Constraints for Table AUDITORIA
--------------------------------------------------------

  ALTER TABLE "SEBAS_CASINO"."AUDITORIA" MODIFY ("TABLA_AFECTADA" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."AUDITORIA" MODIFY ("ID_REGISTRO" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."AUDITORIA" MODIFY ("OPERACION" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."AUDITORIA" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."AUDITORIA" MODIFY ("USUARIO_ORACLE" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."AUDITORIA" ADD CONSTRAINT "CK_AUDITORIA_OP" CHECK (operacion IN ('INSERT','UPDATE','DELETE')) ENABLE;
  ALTER TABLE "SEBAS_CASINO"."AUDITORIA" ADD CONSTRAINT "PK_AUDITORIA" PRIMARY KEY ("ID_AUDITORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CASINO_VIRTUAL"  ENABLE;
