--------------------------------------------------------
--  DDL for Table DATOS_BANCARIOS_USUARIO
--------------------------------------------------------

  CREATE TABLE "SEBAS_CASINO"."DATOS_BANCARIOS_USUARIO" 
   (	"ID_DATOS_BANCARIOS" NUMBER, 
	"ID_USUARIO" NUMBER, 
	"BANCO_ID" VARCHAR2(10 BYTE), 
	"BANCO_NOMBRE" VARCHAR2(100 BYTE), 
	"TIPO_CUENTA" VARCHAR2(20 BYTE), 
	"NUMERO_CUENTA" VARCHAR2(30 BYTE), 
	"TIPO_DOC" VARCHAR2(5 BYTE), 
	"NUMERO_DOC" VARCHAR2(20 BYTE), 
	"NOMBRE_TITULAR" VARCHAR2(200 BYTE), 
	"ACTIVO" NUMBER(1,0) DEFAULT 1, 
	"FECHA_REGISTRO" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CASINO_VIRTUAL" ;
