--------------------------------------------------------
--  Constraints for Table DATOS_BANCARIOS_USUARIO
--------------------------------------------------------

  ALTER TABLE "SEBAS_CASINO"."DATOS_BANCARIOS_USUARIO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."DATOS_BANCARIOS_USUARIO" MODIFY ("BANCO_ID" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."DATOS_BANCARIOS_USUARIO" MODIFY ("TIPO_CUENTA" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."DATOS_BANCARIOS_USUARIO" MODIFY ("NUMERO_CUENTA" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."DATOS_BANCARIOS_USUARIO" MODIFY ("TIPO_DOC" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."DATOS_BANCARIOS_USUARIO" MODIFY ("NUMERO_DOC" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."DATOS_BANCARIOS_USUARIO" MODIFY ("NOMBRE_TITULAR" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."DATOS_BANCARIOS_USUARIO" MODIFY ("ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."DATOS_BANCARIOS_USUARIO" ADD PRIMARY KEY ("ID_DATOS_BANCARIOS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CASINO_VIRTUAL"  ENABLE;
