--------------------------------------------------------
--  Constraints for Table DEPOSITOS
--------------------------------------------------------

  ALTER TABLE "SEBAS_CASINO"."DEPOSITOS" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."DEPOSITOS" MODIFY ("MONTO" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."DEPOSITOS" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."DEPOSITOS" ADD PRIMARY KEY ("ID_DEPOSITO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CASINO_VIRTUAL"  ENABLE;
