--------------------------------------------------------
--  Constraints for Table ESTADO_PARTIDAS
--------------------------------------------------------

  ALTER TABLE "SEBAS_CASINO"."ESTADO_PARTIDAS" MODIFY ("NOMBRE_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."ESTADO_PARTIDAS" ADD CONSTRAINT "PK_ESTADO_PARTIDAS" PRIMARY KEY ("ID_ESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CASINO_VIRTUAL"  ENABLE;
  ALTER TABLE "SEBAS_CASINO"."ESTADO_PARTIDAS" ADD CONSTRAINT "UQ_ESTADO_PARTIDAS_NOMBRE" UNIQUE ("NOMBRE_ESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CASINO_VIRTUAL"  ENABLE;
