REM INSERTING into SEBAS_CASINO.ESTADO_PARTIDAS
SET DEFINE OFF;
Insert into SEBAS_CASINO.ESTADO_PARTIDAS (ID_ESTADO,NOMBRE_ESTADO,DESCRIPCION) values ('1','en curso','Partida activa');
Insert into SEBAS_CASINO.ESTADO_PARTIDAS (ID_ESTADO,NOMBRE_ESTADO,DESCRIPCION) values ('2','ganada','El usuario ganó');
Insert into SEBAS_CASINO.ESTADO_PARTIDAS (ID_ESTADO,NOMBRE_ESTADO,DESCRIPCION) values ('3','perdida','El usuario perdió');
Insert into SEBAS_CASINO.ESTADO_PARTIDAS (ID_ESTADO,NOMBRE_ESTADO,DESCRIPCION) values ('4','cancelada','Partida cancelada');
