--------------------------------------------------------
-- Archivo creado  - jueves-mayo-28-2026   
--------------------------------------------------------
@C:\Users\sebas\Desktop\SEQ_APUESTAS.sql
@C:\Users\sebas\Desktop\SEQ_AUDITORIA.sql
@C:\Users\sebas\Desktop\SEQ_AUDITORIA_USUARIOS.sql
@C:\Users\sebas\Desktop\SEQ_BONOS.sql
@C:\Users\sebas\Desktop\SEQ_CONFIG_JUEGO.sql
@C:\Users\sebas\Desktop\SEQ_DEPOSITOS.sql
@C:\Users\sebas\Desktop\SEQ_ESTADO_PARTIDAS.sql
@C:\Users\sebas\Desktop\SEQ_ESTADO_USUARIO.sql
@C:\Users\sebas\Desktop\SEQ_JUEGOS.sql
@C:\Users\sebas\Desktop\SEQ_LOG_EVENTOS.sql
@C:\Users\sebas\Desktop\SEQ_METODOS_PAGO.sql
@C:\Users\sebas\Desktop\SEQ_PARTIDAS.sql
@C:\Users\sebas\Desktop\SEQ_PROMOCIONES.sql
@C:\Users\sebas\Desktop\SEQ_RETIROS.sql
@C:\Users\sebas\Desktop\SEQ_ROLES.sql
@C:\Users\sebas\Desktop\SEQ_TRANSACCIONES.sql
@C:\Users\sebas\Desktop\SEQ_USUARIO_BONOS.sql
@C:\Users\sebas\Desktop\AUDITORIA.sql
@C:\Users\sebas\Desktop\ESTADO_PARTIDAS.sql
@C:\Users\sebas\Desktop\ESTADO_USUARIO.sql
@C:\Users\sebas\Desktop\JUEGOS.sql
@C:\Users\sebas\Desktop\PARTIDAS.sql
@C:\Users\sebas\Desktop\ROLES.sql
@C:\Users\sebas\Desktop\TRANSACCIONES.sql
@C:\Users\sebas\Desktop\USUARIOS.sql
@C:\Users\sebas\Desktop\VW_BONOS_USUARIO.sql
@C:\Users\sebas\Desktop\VW_DEPOSITOS_PENDIENTES.sql
@C:\Users\sebas\Desktop\VW_DETALLE_APUESTAS.sql
@C:\Users\sebas\Desktop\VW_HISTORIAL_PARTIDAS.sql
@C:\Users\sebas\Desktop\VW_INGRESOS_DIARIOS.sql
@C:\Users\sebas\Desktop\VW_MOVIMIENTOS_MENSUALES.sql
@C:\Users\sebas\Desktop\VW_RENTABILIDAD_JUEGOS.sql
@C:\Users\sebas\Desktop\VW_RESUMEN_ADMIN.sql
@C:\Users\sebas\Desktop\VW_RETIROS_PENDIENTES.sql
@C:\Users\sebas\Desktop\VW_TOP_DEPOSITANTES.sql
@C:\Users\sebas\Desktop\VW_TOP_JUGADORES.sql
@C:\Users\sebas\Desktop\VW_USUARIOS_DETALLE.sql
@C:\Users\sebas\Desktop\AUDITORIA_DATA_TABLE.sql
@C:\Users\sebas\Desktop\ESTADO_PARTIDAS_DATA_TABLE.sql
@C:\Users\sebas\Desktop\ESTADO_USUARIO_DATA_TABLE.sql
@C:\Users\sebas\Desktop\JUEGOS_DATA_TABLE.sql
@C:\Users\sebas\Desktop\PARTIDAS_DATA_TABLE.sql
@C:\Users\sebas\Desktop\ROLES_DATA_TABLE.sql
@C:\Users\sebas\Desktop\TRANSACCIONES_DATA_TABLE.sql
@C:\Users\sebas\Desktop\USUARIOS_DATA_TABLE.sql
@C:\Users\sebas\Desktop\UQ_ROLES_NOMBRE.sql
@C:\Users\sebas\Desktop\UQ_ESTADO_PARTIDAS_NOMBRE.sql
@C:\Users\sebas\Desktop\PK_AUDITORIA.sql
@C:\Users\sebas\Desktop\PK_JUEGOS.sql
@C:\Users\sebas\Desktop\PK_ROLES.sql
@C:\Users\sebas\Desktop\PK_USUARIOS.sql
@C:\Users\sebas\Desktop\UQ_USUARIOS_USERNAME.sql
@C:\Users\sebas\Desktop\PK_PARTIDAS.sql
@C:\Users\sebas\Desktop\PK_ESTADO_PARTIDAS.sql
@C:\Users\sebas\Desktop\PK_TRANSACCIONES.sql
@C:\Users\sebas\Desktop\PK_ESTADO_USUARIO.sql
@C:\Users\sebas\Desktop\UQ_ESTADO_USUARIO_NOMBRE.sql
@C:\Users\sebas\Desktop\UQ_JUEGOS_NOMBRE.sql
@C:\Users\sebas\Desktop\UQ_USUARIOS_CORREO.sql
@C:\Users\sebas\Desktop\TRG_ACTUALIZAR_SALDO.sql
@C:\Users\sebas\Desktop\TRG_AUDITORIA_USUARIOS.sql
@C:\Users\sebas\Desktop\TRG_VALIDAR_SALDO.sql
@C:\Users\sebas\Desktop\PR_ACTUALIZAR_USUARIO.sql
@C:\Users\sebas\Desktop\PR_APLICAR_BONO.sql
@C:\Users\sebas\Desktop\PR_APROBAR_RETIRO.sql
@C:\Users\sebas\Desktop\PR_CAMBIAR_ESTADO.sql
@C:\Users\sebas\Desktop\PR_CASHBACK_SEMANAL.sql
@C:\Users\sebas\Desktop\PR_CONFIRMAR_DEPOSITO.sql
@C:\Users\sebas\Desktop\PR_ELIMINAR_USUARIO.sql
@C:\Users\sebas\Desktop\PR_REALIZAR_RETIRO.sql
@C:\Users\sebas\Desktop\PR_RECHAZAR_DEPOSITO.sql
@C:\Users\sebas\Desktop\PR_RECHAZAR_RETIRO.sql
@C:\Users\sebas\Desktop\PR_REGISTRAR_APUESTA.sql
@C:\Users\sebas\Desktop\PR_REGISTRAR_LOG.sql
@C:\Users\sebas\Desktop\PR_SOLICITAR_DEPOSITO.sql
@C:\Users\sebas\Desktop\PR_SOLICITAR_RETIRO.sql
@C:\Users\sebas\Desktop\PKG_ADMIN.sql
@C:\Users\sebas\Desktop\PKG_PARTIDAS.sql
@C:\Users\sebas\Desktop\PKG_USUARIOS.sql
@C:\Users\sebas\Desktop\PKG_ADMIN_1.sql
@C:\Users\sebas\Desktop\PKG_PARTIDAS_1.sql
@C:\Users\sebas\Desktop\PKG_USUARIOS_1.sql
@C:\Users\sebas\Desktop\FN_CALCULAR_CASHBACK.sql
@C:\Users\sebas\Desktop\FN_OBTENER_APUESTAS_PARTIDA.sql
@C:\Users\sebas\Desktop\FN_OBTENER_LOG_RECIENTE.sql
@C:\Users\sebas\Desktop\JUEGOS_CONSTRAINT.sql
@C:\Users\sebas\Desktop\AUDITORIA_CONSTRAINT.sql
@C:\Users\sebas\Desktop\ESTADO_USUARIO_CONSTRAINT.sql
@C:\Users\sebas\Desktop\USUARIOS_CONSTRAINT.sql
@C:\Users\sebas\Desktop\ROLES_CONSTRAINT.sql
@C:\Users\sebas\Desktop\TRANSACCIONES_CONSTRAINT.sql
@C:\Users\sebas\Desktop\ESTADO_PARTIDAS_CONSTRAINT.sql
@C:\Users\sebas\Desktop\PARTIDAS_CONSTRAINT.sql
@C:\Users\sebas\Desktop\PARTIDAS_REFCONSTRAINT.sql
@C:\Users\sebas\Desktop\TRANSACCIONES_REFCONSTRAINT.sql
@C:\Users\sebas\Desktop\USUARIOS_REFCONSTRAINT.sql
