--------------------------------------------------------
--  Constraints for Table JUEGOS
--------------------------------------------------------

  ALTER TABLE "SEBAS_CASINO"."JUEGOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."JUEGOS" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."JUEGOS" ADD CONSTRAINT "CK_JUEGOS_ESTADO" CHECK (estado IN ('activo', 'inactivo')) ENABLE;
  ALTER TABLE "SEBAS_CASINO"."JUEGOS" ADD CONSTRAINT "PK_JUEGOS" PRIMARY KEY ("ID_JUEGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CASINO_VIRTUAL"  ENABLE;
  ALTER TABLE "SEBAS_CASINO"."JUEGOS" ADD CONSTRAINT "UQ_JUEGOS_NOMBRE" UNIQUE ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CASINO_VIRTUAL"  ENABLE;
