--------------------------------------------------------
--  DDL for Table LOG_EVENTOS
--------------------------------------------------------

  CREATE TABLE "SEBAS_CASINO"."LOG_EVENTOS" 
   (	"ID_LOG" NUMBER, 
	"TIPO_EVENTO" VARCHAR2(50 BYTE), 
	"NIVEL" VARCHAR2(10 BYTE), 
	"ID_USUARIO" NUMBER, 
	"IP_ORIGEN" VARCHAR2(50 BYTE), 
	"MODULO" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(2000 BYTE), 
	"FECHA" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CASINO_VIRTUAL" ;
