--------------------------------------------------------
--  Constraints for Table LOG_EVENTOS
--------------------------------------------------------

  ALTER TABLE "SEBAS_CASINO"."LOG_EVENTOS" MODIFY ("TIPO_EVENTO" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."LOG_EVENTOS" MODIFY ("NIVEL" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."LOG_EVENTOS" MODIFY ("MODULO" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."LOG_EVENTOS" ADD PRIMARY KEY ("ID_LOG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CASINO_VIRTUAL"  ENABLE;
