--------------------------------------------------------
--  Constraints for Table METODOS_PAGO
--------------------------------------------------------

  ALTER TABLE "SEBAS_CASINO"."METODOS_PAGO" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."METODOS_PAGO" MODIFY ("ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."METODOS_PAGO" ADD PRIMARY KEY ("ID_METODO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CASINO_VIRTUAL"  ENABLE;
