--------------------------------------------------------
--  Ref Constraints for Table PARTIDAS
--------------------------------------------------------

  ALTER TABLE "SEBAS_CASINO"."PARTIDAS" ADD CONSTRAINT "FK_PARTIDAS_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "SEBAS_CASINO"."USUARIOS" ("ID_USUARIO") ENABLE;
  ALTER TABLE "SEBAS_CASINO"."PARTIDAS" ADD CONSTRAINT "FK_PARTIDAS_JUEGO" FOREIGN KEY ("ID_JUEGO")
	  REFERENCES "SEBAS_CASINO"."JUEGOS" ("ID_JUEGO") ENABLE;
  ALTER TABLE "SEBAS_CASINO"."PARTIDAS" ADD CONSTRAINT "FK_PARTIDAS_ESTADO" FOREIGN KEY ("ID_ESTADO")
	  REFERENCES "SEBAS_CASINO"."ESTADO_PARTIDAS" ("ID_ESTADO") ENABLE;
