--------------------------------------------------------
--  Constraints for Table PARTIDAS
--------------------------------------------------------

  ALTER TABLE "SEBAS_CASINO"."PARTIDAS" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."PARTIDAS" MODIFY ("ID_JUEGO" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."PARTIDAS" MODIFY ("ID_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."PARTIDAS" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."PARTIDAS" MODIFY ("APUESTA" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."PARTIDAS" MODIFY ("GANANCIA" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."PARTIDAS" ADD CONSTRAINT "CK_PARTIDAS_APUESTA" CHECK (apuesta > 0) ENABLE;
  ALTER TABLE "SEBAS_CASINO"."PARTIDAS" ADD CONSTRAINT "CK_PARTIDAS_GANANCIA" CHECK (ganancia >= 0) ENABLE;
  ALTER TABLE "SEBAS_CASINO"."PARTIDAS" ADD CONSTRAINT "PK_PARTIDAS" PRIMARY KEY ("ID_PARTIDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CASINO_VIRTUAL"  ENABLE;
