--------------------------------------------------------
--  DDL for Table PARTIDAS
--------------------------------------------------------

  CREATE TABLE "SEBAS_CASINO"."PARTIDAS" 
   (	"ID_PARTIDA" NUMBER, 
	"ID_USUARIO" NUMBER, 
	"ID_JUEGO" NUMBER, 
	"ID_ESTADO" NUMBER, 
	"FECHA" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"APUESTA" NUMBER(12,2), 
	"GANANCIA" NUMBER(12,2) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CASINO_VIRTUAL" ;
