--------------------------------------------------------
--  DDL for Table RETIROS
--------------------------------------------------------

  CREATE TABLE "SEBAS_CASINO"."RETIROS" 
   (	"ID_RETIRO" NUMBER, 
	"ID_USUARIO" NUMBER, 
	"ID_METODO" NUMBER, 
	"MONTO" NUMBER(12,2), 
	"ESTADO" VARCHAR2(20 BYTE) DEFAULT 'pendiente', 
	"FECHA_SOLICITUD" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"FECHA_PROCESAMIENTO" TIMESTAMP (6), 
	"ID_ADMIN_REVISOR" NUMBER, 
	"REFERENCIA_WOMPI" VARCHAR2(100 BYTE), 
	"MOTIVO_RECHAZO" VARCHAR2(500 BYTE), 
	"PAYOUT_ID" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CASINO_VIRTUAL" ;
