REM INSERTING into SEBAS_CASINO.RETIROS
SET DEFINE OFF;
Insert into SEBAS_CASINO.RETIROS (ID_RETIRO,ID_USUARIO,ID_METODO,MONTO,ESTADO,FECHA_SOLICITUD,FECHA_PROCESAMIENTO,ID_ADMIN_REVISOR,REFERENCIA_WOMPI,MOTIVO_RECHAZO,PAYOUT_ID) values ('1','4',null,'2220','pendiente',to_timestamp('28/05/26 11:25:49,499000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),null,null,null,null,null);
Insert into SEBAS_CASINO.RETIROS (ID_RETIRO,ID_USUARIO,ID_METODO,MONTO,ESTADO,FECHA_SOLICITUD,FECHA_PROCESAMIENTO,ID_ADMIN_REVISOR,REFERENCIA_WOMPI,MOTIVO_RECHAZO,PAYOUT_ID) values ('21','4',null,'10000','pendiente',to_timestamp('29/05/26 09:18:26,029000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),null,null,null,null,null);
