--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "SEBAS_CASINO"."ROLES" MODIFY ("NOMBRE_ROL" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."ROLES" ADD CONSTRAINT "PK_ROLES" PRIMARY KEY ("ID_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CASINO_VIRTUAL"  ENABLE;
  ALTER TABLE "SEBAS_CASINO"."ROLES" ADD CONSTRAINT "UQ_ROLES_NOMBRE" UNIQUE ("NOMBRE_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CASINO_VIRTUAL"  ENABLE;
