--------------------------------------------------------
--  DDL for Sequence SEQ_AUDITORIA_USUARIOS
--------------------------------------------------------

   CREATE SEQUENCE  "SEBAS_CASINO"."SEQ_AUDITORIA_USUARIOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
