--------------------------------------------------------
--  DDL for Table TRANSACCIONES
--------------------------------------------------------

  CREATE TABLE "SEBAS_CASINO"."TRANSACCIONES" 
   (	"ID_TRANSACCION" NUMBER, 
	"ID_USUARIO" NUMBER, 
	"TIPO" VARCHAR2(10 BYTE), 
	"MONTO" NUMBER(12,2), 
	"FECHA" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"DESCRIPCION" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CASINO_VIRTUAL" ;
