--------------------------------------------------------
--  Constraints for Table TRANSACCIONES
--------------------------------------------------------

  ALTER TABLE "SEBAS_CASINO"."TRANSACCIONES" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."TRANSACCIONES" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."TRANSACCIONES" MODIFY ("MONTO" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."TRANSACCIONES" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."TRANSACCIONES" ADD CONSTRAINT "CK_TRANSACCIONES_TIPO" CHECK (tipo IN ('deposito','ganancia','perdida','retiro')) ENABLE;
  ALTER TABLE "SEBAS_CASINO"."TRANSACCIONES" ADD CONSTRAINT "CK_TRANSACCIONES_MONTO" CHECK (monto > 0) ENABLE;
  ALTER TABLE "SEBAS_CASINO"."TRANSACCIONES" ADD CONSTRAINT "PK_TRANSACCIONES" PRIMARY KEY ("ID_TRANSACCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CASINO_VIRTUAL"  ENABLE;
