--------------------------------------------------------
--  DDL for Table USUARIO_BONOS
--------------------------------------------------------

  CREATE TABLE "SEBAS_CASINO"."USUARIO_BONOS" 
   (	"ID_USUARIO_BONO" NUMBER, 
	"ID_USUARIO" NUMBER, 
	"ID_BONO" NUMBER, 
	"MONTO_APLICADO" NUMBER(12,2), 
	"FECHA_APLICADO" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"ESTADO" VARCHAR2(20 BYTE) DEFAULT 'aplicado', 
	"DESCRIPCION" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CASINO_VIRTUAL" ;
