--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "SEBAS_CASINO"."USUARIOS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."USUARIOS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."USUARIOS" MODIFY ("NOMBRE_1" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."USUARIOS" MODIFY ("APELLIDO_1" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."USUARIOS" MODIFY ("CORREO" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."USUARIOS" MODIFY ("FECHA_NACIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."USUARIOS" MODIFY ("SALDO" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."USUARIOS" MODIFY ("ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."USUARIOS" MODIFY ("ID_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."USUARIOS" MODIFY ("FECHA_REGISTRO" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."USUARIOS" ADD CONSTRAINT "CK_USUARIOS_SALDO" CHECK (saldo >= 0) ENABLE;
  ALTER TABLE "SEBAS_CASINO"."USUARIOS" ADD CONSTRAINT "PK_USUARIOS" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CASINO_VIRTUAL"  ENABLE;
  ALTER TABLE "SEBAS_CASINO"."USUARIOS" ADD CONSTRAINT "UQ_USUARIOS_USERNAME" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CASINO_VIRTUAL"  ENABLE;
  ALTER TABLE "SEBAS_CASINO"."USUARIOS" ADD CONSTRAINT "UQ_USUARIOS_CORREO" UNIQUE ("CORREO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CASINO_VIRTUAL"  ENABLE;
