--------------------------------------------------------
--  Constraints for Table USUARIO_BONOS
--------------------------------------------------------

  ALTER TABLE "SEBAS_CASINO"."USUARIO_BONOS" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."USUARIO_BONOS" MODIFY ("ID_BONO" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."USUARIO_BONOS" MODIFY ("MONTO_APLICADO" NOT NULL ENABLE);
  ALTER TABLE "SEBAS_CASINO"."USUARIO_BONOS" ADD PRIMARY KEY ("ID_USUARIO_BONO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CASINO_VIRTUAL"  ENABLE;
