--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "SEBAS_CASINO"."USUARIOS" 
   (	"ID_USUARIO" NUMBER, 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(64 BYTE), 
	"NOMBRE_1" VARCHAR2(50 BYTE), 
	"NOMBRE_2" VARCHAR2(50 BYTE), 
	"APELLIDO_1" VARCHAR2(50 BYTE), 
	"APELLIDO_2" VARCHAR2(50 BYTE), 
	"CORREO" VARCHAR2(100 BYTE), 
	"FECHA_NACIMIENTO" DATE, 
	"SALDO" NUMBER(12,2) DEFAULT 0, 
	"ID_ROL" NUMBER, 
	"ID_ESTADO" NUMBER, 
	"FECHA_REGISTRO" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CASINO_VIRTUAL" ;
